# Generated by Django 4.1 on 2022-08-24 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('short_description', models.CharField(max_length=300, verbose_name='Краткое описание')),
                ('description', models.TextField(default='Описание', verbose_name='Задача')),
                ('isComplete', models.BooleanField(default=False, verbose_name='Выполенено')),
                ('importance_task', models.CharField(choices=[('AA', 'Высокий'), ('BB', 'Средний'), ('CC', 'Низкий')], default='BB', max_length=30, verbose_name='Важность задачи')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
