# Generated by Django 4.1 on 2022-11-29 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todoApi', '0003_alter_task_creator_alter_task_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcomment',
            name='task_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_task', to='todoApi.task'),
        ),
    ]
