# Generated by Django 4.1 on 2022-12-01 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoApi', '0004_alter_taskcomment_task_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskcomment',
            old_name='task_comment',
            new_name='task',
        ),
    ]
