# Generated by Django 4.1 on 2022-12-07 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todoApi', '0005_rename_task_comment_taskcomment_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskcomment',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='taskcomment',
            name='task',
        ),
        migrations.AddField(
            model_name='taskcomment',
            name='comment_creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskcomment',
            name='comment_task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='task', to='todoApi.task'),
            preserve_default=False,
        ),
    ]
