# Generated by Django 4.1 on 2022-12-07 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todoApi', '0006_remove_taskcomment_creator_remove_taskcomment_task_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskcomment',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='taskcomment',
            name='comment_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='todoApi.task'),
        ),
    ]
