# Generated by Django 4.1 on 2023-01-17 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoApi', '0007_alter_taskcomment_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='creator',
            new_name='task_creator',
        ),
    ]
