# Generated by Django 4.1 on 2023-01-18 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApi', '0008_rename_creator_task_task_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='departament',
            field=models.CharField(blank=True, choices=[('Development', 'Разработка'), ('Services', 'Сервисы'), ('Management', 'Менеджмент')], max_length=30, verbose_name='Департамент'),
        ),
    ]
