# Generated by Django 4.1 on 2022-08-24 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_todouser_send_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='todouser',
            name='first_name',
            field=models.CharField(db_index=True, default='wow', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
