# Generated by Django 4.1 on 2022-08-24 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_todouser_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todouser',
            name='first_name',
        ),
    ]
