# Generated by Django 4.1 on 2022-08-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_todouser_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='todouser',
            name='first_name',
            field=models.CharField(blank=True, db_index=True, max_length=100, unique=True),
        ),
    ]
