# Generated by Django 4.1 on 2022-08-30 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_todouser_login_field_alter_todouser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todouser',
            name='login_field',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
