# Generated by Django 4.1 on 2022-08-30 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_todouser_login_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todouser',
            name='login_field',
            field=models.CharField(max_length=250),
        ),
    ]
