# Generated by Django 4.1 on 2022-08-31 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_alter_todouser_login_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todouser',
            name='login_field',
        ),
    ]
