# Generated by Django 4.1 on 2023-01-18 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_remove_todouser_login_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todouser',
            name='departament',
            field=models.CharField(choices=[('Development', 'Разработка'), ('Services', 'Сервисы'), ('Management', 'Менеджмент')], default='Development', max_length=30, verbose_name='Направление'),
        ),
    ]
